
var CN={
	"Login":'登录',//登录页
	"Register":'注册',
	"Forgot":'找回密码',
	"Mobile":"手机号码：",
	"Password":"登录密码：",
	"EnterMobile":"请输入手机号码",
	"EnterPassword":"请输入登录密码",
	"ReferralID":"邀请码：",
	"EnterreferralID":"请输入邀请码",
	"Next":"下一步",
	"Verifycode":"验证码：",
	"SendSMS":"获取验证码",
	"EnterSMS":"请输入验证码",
	"ConfirmPassword":"确认密码：",
	"Confirmloginpassword":"请确认登录密码",
	"PaymentPassword":"交易密码：",
	"CreatePaymentpassword":"请输入交易密码",
	"ConfirmPaymentpassword":"请确认交易密码",
	"Finish":"完成",
	"CreatenewPassword":"设置新密码",
	"EnternewPassword":"请输入新密码",
	"ConfirmnewPassword":"确认新密码",
	"EnterrepeatnewPassword":"请重复新密码",
	"indexTransfer":"转 账",//首页
	"ReceiptCode":"收款码",
	"Reward1":"红 包",
	"Token":"通证",
	"History":"明细",
	"Asset":"资产",
	"Convert":"兑换",
	"TokenService":"通证服务",
	"Activatefriend":"激活好友",
	"Node":"节点",
	"Contract":"智能合约",
	"POS":"POS权益",
	"DPOS":"DPOS权益",
	"LifeService":"生活服务",
	"Help":"联系客服",
	"FuelCard":"福利大转盘",
	"Booking":"订票",
	"ANTcloudpurchase":"蚂蚁云购",
	"Dripping":"滴滴打车",
	"Game":"游戏",
	"Takeaway":"外卖",
	"Information":"资讯",
	"More":"更多",
	"Home":"首页",
	"Wallet":"钱包",
	"Trades":"交易",
	"Mall":"商场",
	"Receipt Code1":"商户收款码",
	"nickname666":"昵称:",
	"Accounts666":"账号:",
	"Sweep to transfer money to me":"扫一扫向我转账",
	"Save to album":"保存至相册",
	"IdentityAuthentication":"实名认证",//侧边栏
	"Security":"安全中心",
	"Message":"消息中心",
	"Versiondetection":"版本检测",
	"Aboutus":"关于我们",
	"Settings":"系统设置",
	"Logout":"退出登录",
	"Transfer":"转账",//转账
	"Choosetransfermethod":"Choose transfer method",
	"Directtransfer":"Direct transfer",
	"Scantotransfer":"Scan to transfer",
	"Callprefix":"对方冠码：",
	"Transferredaccount":"转入账户：",
	"Fillinthetransferaccount":"请填写转入账户",
	"Pleaseconfirmthattheaccountiscorrectandavoidtheloss":"请再次确认账号无误，避免造成损失",
	"Transfercoins":"转出币种：",
	"Quantitytransferred":"转入数量：",
	"AvailableToken":"可用通证：",
	"Actualtransfer":"实际转出：",
	"Transactionconfirmation":"交易确认",
	"History1":"转出交易详情",
	"Transferredaccount1":"转入账户",
	"Enternickname":"转入昵称",
	"Theusername":"用户姓名",
	"Transferamount":"转入数额",
	"SelectCoin":"交易币种",
	"Fee":"手续费率：",
	"Latestarrivaltime":"最迟到账时间",
	"Estimatedarrivaltime":"预计到账时间",
	"Thenextdaybeforearrives":"次日24:00前到账",
	"Confirm":"确认无误",
	"Cancel":"重新填写",
	"Enterpaymentpassword":"输入支付密码",
	"Forgottopaymentpassword":"忘记支付密码",
	"Pleasewait":"请您耐心等待...",
	"Burning":"燃烧",
	"Transactioncreation":"交易创建",
	"InformationCollection":"信息采集",
	"TransactionEncryption":"交易加密",
	"SafetyVerification":"安全验证",
	"SendTheTransactionRequest":"发送交易请求",
	"Success":"完成",
	"Pass":"通过",
	"CLR":"清空",
	"DEL":"删除",
	"Transresult":"交易结果",
	"SFA":"成功",
	"CFM":"确认",
	"Remarks：":"备注：",
	"Remarks":"备注",
	"Fill Remarks":"填写备注",
	"ReceiptCode":"收款码",//收款码
	"SweeptheQRcodeonthetopandtransfertoeachother":"扫一扫上面的二维码，可互相转账",
	"5":"主人，暂未发现有红包",//红包
	"Assetshistory":"资产详情",//资产详情
	"Assetcomposition":"资产组成",
	"AvailableToken":"可用通证",
	"Assets":"资产数量",
	"Converttoassets":"兑换资产",
	"History2":"收支记录",
	"Transferout":"转出",
	"Transfer":"转入",
	"Converttoassets1":"兑换窗",//兑换资产
	"Tokens":"通证数量",
	"Convertquantity":"兑换数量",
	"Enterquantity":"请输入数量",
	"Afterconvert":"兑换后",
	"5":"兑换成功",
	"5":"确认",
	"Communityfriends":"社区好友",//社区好友
	"Numberofinvitations":"邀请人数：",
	"Nickname1":"昵称",
	"Username":"用户名",
	"Status":"激活状态",
	"Pleasechoosethedistributionmethod":"请选择分配方式",
	"Defaultallocationnode":"默认分配节点",
	"Manuallyassignnodes":"手动分配节点",
	"Areyousureassigndefaultcontacts":"是否确认分配默认接点",
	"Confirm":"确定",
	"Cancel":"取消",
	"Bindingcontact":"接点绑定",
	"Contactmark":"接点标识",
	"Entercontactmark":"请输入接点标识",
	"Nodeinformation":"节点信息",
	"Search":"搜索",
	"Pleaseconfirm":"请确认接点信息无误，一旦激活将无法修改",
	"Confirmactivationoffriends":"确认激活好友",
	"MyNode":"我的节点",//我的节点
	"T1Node":"T1节点",
	"Nodereward":"节点奖励>>",
	"Assets1":"资产量：",
	"Numberofnodes":"节点量：",
	"Referee":"推荐人：",
	"T2Node":"T2节点",
	"Nodereward1":"节点奖励",//节点奖励
	"YesterdayTokenreward":"昨日通证奖励",
	"CumulativeTokenreward":"累计通证奖励",
	"Yesterdayassetaward":"昨日资产奖励",
	"Cumulativeassetaward":"累计资产奖励",
	"Noderewarddescription":"节点奖励说明",
	"Recentnodereward":"近期节点奖励",
	"Reward":"奖励",
	"Invitationcard":"邀请卡",//邀请卡
	"InviteFriends":"好友邀请",
	"ReferralID1":"邀请码",
	"ScanQRcode":"扫描二维码",
	"RegistertheANTaccount ":"注册ANT新用户",
	"Posdescription":"Pos奖励说明",//POS
	"RecentPos":"近期Pos奖励",
	"DPOSdescription":"Dpos奖励说明",//DPOS
	"Todayassetaward":"今日资产奖励",
	"Tokenrewardtoday":"今日通证奖励",
	"RecentDPOS":"近期Dpos奖励",
	"Accountlock":"账户锁",//安全中心
	"Openprotectedaccountisnothacked":"开启保护账号不被盗号",
	"Regionallock":"地域锁",
	"Openthegeographicalmodetoprotecttheaccountfrombeinghacked":"开启地域模式保护账号不被盗号",
	"Pattern":"手势密码",
	"OpenwhenAPPislocked":"同于打开APP解锁时使用",
	"ChangeLoginpassword":"登录密码修改",
	"Usedforaccountlogin":"用于账户登录使用",
	"ChangePaymentpassword":"支付密码修改",
	"Usewhenchangingaccountfunds":"用于账户资金变动时使用",
	"Changephonenumber":"修改手机认证",
	"Changetheoriginalboundphonenumber":"用于修改登录使用",
	"Changepaymentpassword":"找回支付密码",
	"Usewhenchangingaccountfunds":"用于找回支付密码使用",
	"E-mailsecurity":"修改邮箱密码",
	"ChangetheoriginalboundE-mail":"用于修改邮箱登录密码使用",
	"ChangeLoginPassword":"修改登录密码",//修改登录密码
	"Enteroldpassword":"请输入旧密码",
	"Enteroldpassword1":"请输入旧密码：",
	"Enternewpassword":"请输入新密码",
	"Enternewpassword1":"请输入新密码：",
	"ConfirmNewPassword":"请确认新密码",
	"ConfirmNewPassword1":"请确认新密码：",
	"Submit":"提交",
	"ChangePaymentpassword":"修改支付密码",//修改支付密码
	"Changephonenumber":"修改手机认证",//修改手机认证
	"Newphonenumber":"新手机号码：",
	"Newcallprefix":"新手机冠码：",
	"Paymentpassword":"支付密码：",
	"Confirmagain":"请确认支付密码",
	"Enteranewpaymentpassword":"请输入新支付密码",
	"Walletassetsvalue":"钱包资产估值",//钱包
	"Deposit":"充值",
	"Withdrawal":"提现",
	"History":"明细",
	"Assethistory":"资产明细",
	"Frozen":"冻结",
	"Buy":"发布购买",//交易
	"Sell":"发布出售",
	"Crowd-funding":"众筹",
	"Transactionservice":"交易服务",
	"Orders":"委托单",
	"Trading":"交易中",
	"OK":"交易完成",
	"Orderhistory":"交易记录",
	"Creditrecord":"信用记录",
	"Workorder":"工单",
	"Bankcard":"银行卡",
	"Complaints&Suggestions":"投诉建议",
	"Mallentrance":"商城入口",//商城
	"Buildingaglobalbusinessalliance":"打造全球商业大联盟",//联系客服
	"CSR(WeChat)":"ANT客服微信：",
	"CSR(QQ)":"商城客服微信：",
	"CSR(QQ)01":"ANT客服QQ：",
	"Copy":"复制",
	"VIP":"会员专区",
	"AllCategories":"全部分类",
	"WelcomeToANTMall":"欢迎来到蚂蚁商城",
	"TransactionDetails":"交易详情",//交易详情
	"Orderinformation":"订单信息",
	"Ordernumber":"订单编号",
	"Typeoftransaction":"交易类型",
	"Transactiontime":"成交时间",
	"Disburserinformation":"支出方信息",
	"Spendingaccount":"支出账户",
	"Accountnickname":"账户昵称",
	"Coins":"交易币种",
	"Fee1":"燃烧",
	"Tokenchange":"通证变动",
	"Assetchange":"资产变动",
	"Payeeinformation":"收款方信息",
	"Receivingaccount":"收入账户",
	"Receiverinformation":"收入方信息",
	"History3":"收支详情",
	"Detailsoffriends":"好友详情",//好友详情
	"Friendinformation":"好友信息：",
	"Contactperson":"接点人：",
	"return":"返回",//国家选择
	"Choosethecountry":"国家选择",
	"rewarddescription":"奖励说明",//奖励说明
	"(Currentversion)":"(当前版本)",//版本检测
	"VersionInformation":"版本信息",
	"Latestversion":"最新版本",
	"Releasetime":"发布时间",
	"Installationpackagesize":"安装包大小",
	"Updatecontent":"更新内容",
	"Contract Scratch":"旦愿有鲤",//合约刮刮
	"Rule Of Activity":"活动规则",
	"1101":"旦愿有鲤<br/>元旦囤年货，锦鲤就是你。<br/>ANT合约刮刮自推出以来，市场反应空前热烈。<br/>为了响应广大会员的强烈要求，同时祝贺ANT MALL盛大开启，<br/>ANT锦鲤风靡来袭，福利继续传递！<br/>50万ANT Token等你来领取，助力元旦囤年货！<br/>你的年货，ANT帮你囤！",
	"1102":"所有ANT注册会员，刮奖一次消耗100ANT（所有参与者均可获得100资产奖励，相当于免费刮奖），2019年1月1日中午12点准时开始，限量5000张先到先得，刮完即止。 ",
	"Award Setting：":"奖项设置：",
	"First prize 2 places:50000ANT":"一等奖2名：50000ANT",
	"Second prize 10 places:10000ANT":"二等奖10名：10000ANT",
	"Third prize 100 places:1000ANT":"三等奖100名：1000ANT",
	"Fourth prize 500 places:200ANT":"四等奖1000名：200ANT",
	"All participants receive 100 asset awards":"所有参与者均可获得100资产奖励",
	"Note: The final interpretation of this activity belongs to ANT Team":"注：本活动最终解释权归ANT 基金会所有。",
	"Receive":"领奖",
	"Come again":"再来一次",
	"Exit":"退出",
	"History03":"详细记录",
	"Winning":"中奖啦",
	"Congratulations Lucky prize":"恭喜您获得幸运奖",
	"Congratulations 1st prize":"恭喜您获得一等奖",
	"Congratulations 2nd prize":"恭喜您获得二等奖",
	"Congratulations 3rd prize":"恭喜您获得三等奖",
	"Congratulations 4th prize":"恭喜您获得四等奖",
	"Lucky prize":"幸运奖",
	"1st prize":"一等奖",
	"2nd prize":"二等奖",
	"3rd prize":"三等奖",
	"4th prize":"四等奖",
	"Deposit in wallet":"存入钱包",
	"Scratch history":"合约刮刮记录",
	"Date":"参与时间",
	"Winning user":"中奖用户",
	"Winning result":"中奖结果",
	"Scratch rewards":"刮奖奖励",
	"Welfare Draw":"福利大转盘",//福利大转盘
	"The number of draws currently held":"当前可抽奖次数：",
	"Thank you":"再接再厉",
	"Come again":"再来一次",
	"Winning history":"中奖记录>>",
	"Activity description":"活动说明",
	"1Assets":"1资产",
	"10Assets":"10资产",
	"100Assets":"100资产",
	"1000Assets":"1000资产",
	"10000Assets":"10000资产",
	"100000Assets":"100000资产",
	"WelfareText":"ANT自上线至今，短短几个月的时间，会员数量呈爆发性增长，为感谢新老会员对ANT的支持与厚爱，ANT特推出福利大转盘活动，感恩回馈新老会员活动期间，每邀请一位有效好友，和新注册的有效用户，都会获得1次免费抽奖机会。最高10万资产等你来拿，还在等什么，赶紧邀请好友一起来抽奖吧！",
	"WelfareText1":"注：有效用户指将通证兑换100资产以上",
	"WelfareText2":"本次活动最终解释权归ANT所有",
	"Winning history1":"中奖记录",
	"Announcement":"通知公告",//通知公告
	"Fill in business information":"填写商户信息",//商户收款码
	"Collection account:":"收款账号:",
	"Product name:":"产品名称:",
	"Unit Price:":"产品单价:",
	"Mobile phone:":"联系方式:",
	"Product Description:":"产品说明:",
	"Generate a color QR code":"生成收款二维码",
	"Generate a monochrome QR code":"生成黑白二维码",
	"Product Description":"产品介绍",
	"Save to phone album":"保存至手机",
	"Lucky red packet":"锦鲤红包",//锦鲤红包
	"History of red packets":"红包记录",
	"shake":"摇一摇",
	"Grab the asset red packet":"抢资产红包",
	"Distribute red packets":"发红包",
	"Red packet type":"红包类型",
	"Ordinary red packet":"普通红包",
	"RedAmounts":"红包金额",
	"Please enter the amounts":"请输入红包金额",
	"Friend account":"好友号码",
	"Friends Mobile Number":"好友手机号码",
	"Messages":"红包留言",
	"Good fortune":"恭喜发财 大吉大利",
	"Confirm send":"确认发送",
	"Amount or number of red packets not filled in":"金额或红包个数未填写",
	"Amount does not match":"金额不符",
	"RedNumber":"红包个数",
	"Please enter the number":"请输入红包个数",
	"Sending mode":"发送方式",
	"Fixed amount":"固定金额",
	"Random amount":"随机金额",
	"Selection area":"选择区域",
	"Ordinary red packet1":"发普通红包",
	"Area red packet":"发区域红包",
	"Area red packet1":"区域红包",
	"Congratulations on receiving a red packet of assets":"恭喜您获得一个资产红包",
	"Valid on the day":"仅当天有效",
	"Congratulations on receiving the asset red packet":"恭喜获得资产红包",
	"Deposit into assets":"存入资产",
	"My red packet":"我的红包",
	"Friends":"好友",
	"Add":"添加",
	"Mobile5":"手机号码",
	"RedEnvelopeTitle":"ANT红包功能介绍：",
	"RedEnvelopeText1":"在中国传统春节到来之际，ANT红包功能正式上线啦！",
	"RedEnvelopeText2":"小伙伴们可以用资产给亲朋好友们发贺年红包啦，送上祝福，带去好运！",
	"RedEnvelopeText3":"今年过节不收礼，收礼只收ANT。",
	"RedEnvelopeText4":"区域红包：选择某个省、市、地区，输入资产数量后，点击发送即可让该区域所有会员通过ANT摇一摇领取到你的祝福红包。发送区域红包每次限制2000资产以内，每日发送最高不超过10000资产；收取区域红包每日不超过2000资产。",
	"RedEnvelopeText5":"普通红包：输入亲朋好友的ANT账号后，输入资产数量，即可把祝福和好运以红包的形式发给亲朋好友。单个普通红包不能超过100资产，每天发送上限为1000资产；收取普通红包每天不能超过1000资产。",
	"RedEnvelopeText6":"活动介绍",
	//2.0版本所需文案
	"loging2.0_1":"忘记密码",
	"loging2.0_2":"私钥登录",
	"loging2.0_3":"注册",
	"loging2.0_4":"导入私钥",
	"loging2.0_5":"账号密码",
	"loging2.0_6":"私钥安全小课堂",
	"loging2.0_7":"为了您的资产安全，请仔细阅读以下协议",
	"loging2.0_8":"私钥，是掌握数字钱包的入口，只有私钥，才能证明你是钱包里资产的主人，而且这串私钥除了你之外，没有任何人知道；这是去中心化和中心化最大的区别，你的数字资产，由你自己掌控，没有中心化的机构介入其中。",
	"loging2.0_9":"私钥是采用“椭圆曲线加密算法”生成的一个32字节随机数，由64个十六进制的字符组成，而且一个钱包只有一个私钥，不能修改，是您个人在链上的唯一的身份凭证，一个私钥可以对应多个公钥，而每个公钥可以对应一个地址，地址是通过公钥进行一些数学逻辑变换转换而来，在知晓地址或者公钥时无法推算私钥，而知晓私钥，则可以推算公钥与地址。",
	"loging2.0_10":"区块链具有“匿名性”特点，除用户公开承认和证明某个地址的私钥归自身所拥有，否则没有任何方式知晓持有地址资产的用户的真实信息。完全不需要担心隐私泄露问题。",
	"loging2.0_11":"助记词通常是由一段12个随机单词组成的，换句话说助记词就是另一种形式的私钥。它通过算法将64位的私钥转换成若干个常见的英文单词，或其他语言版本的词汇。",
	"loging2.0_12":"你可以把助记词理解为私钥的不同表现形式，需要备份，且备份时尽量用纸笔记录下来，可以让家人保管一份，自己保管一份，不要保存在网络上，如云笔记，聊天记录等，如果更换手机电脑，通过备份，可以帮你恢复钱包。你可以通过助记词导入钱包, 但反过来讲, 如果他人得到了你的助记词, 就可以转移你的资产, 所以要妥善保管自己的助记词。",
	"loging2.0_13":"若私钥丢失或忘记私钥密码，没有备份助记词，便等同于失去唯一凭证，私钥对应的地址内的所有资产将永久遗失，没有任何方法进行转移与交易，也无法通过任何外界手段进行资产的找回。",
	"loging2.0_14":'明文私钥: 64 位的 16 进制哈希值字符串, 用一句话阐述明文私钥的重要性 "谁掌握了私钥, 谁就掌握了该钱包的使用权!"',
	"loging2.0_15":"区块链的世界和现实还是有点不同，打个比方，如果你银行卡密码忘记了，你能本人拿身份证去银行重置下密码。而数字钱包的私钥，你忘记了，又没有备份助记词，那谁都帮不了你，联系客服，提供手机验证码，钱包地址等等都无法找回，因为这是去中心化的DAPP，不会存储用户的私钥，所有私钥都只存储在用户本地。",
	"loging2.0_16":"你可以在同一台手机上测试，也可以再另外一台手机上测试来验证是否备份准确。",
	"loging2.0_17":"同一台手机导入，如果原来钱包存在的，会告诉你钱包已存在，说明备份得对的。",
	"loging2.0_18":"不同手机导入，可以导入成功，名字虽然不一样，但是地址是一模一样的，说明也是备注得也对的。",
	"loging2.0_19":"我已阅读理解该使用协议，并且愿意遵循此协议。",
	"loging2.0_20":"下一步,开始测验",
	"loging2.0_21":"私钥安全小测试",
	"loging2.0_22":"1.私钥是您个人在链上的唯一的身份凭证，若私钥丢失或忘记私钥密码，将无法通过任何途径进行找回？",
	"loging2.0_23":"正确,私钥采用“椭圆曲线加密算法”生成，以普通计算机的计算能力,私钥如若丢失，将无法找回。",
	"loging2.0_24":"错误，丢失后，可以使用手机号码和验证码进行找回。",
	"loging2.0_25":"2.在《ANT Token》中创建的私钥，若我不慎遗失，可以通过联系客服，并且提供手机号码，验证码，钱包地址进行找回？",
	"loging2.0_26":"无法找回，《ANT Token》使用的所有私钥均又用户生成时使用的设备进行计算而来，作为一个“去中心化”的Dapp，《ANT Token》并未备份任何用户私钥。",
	"loging2.0_27":"是的，可以通过ANT私钥安全中心进行找回。",
	"loging2.0_28":"3.私钥、公钥、地址之间的概念描述正确的是？",
	"loging2.0_29":"私钥、公钥，地址之间可以进行随意转换，只要知道其中一项则可以推算其他任意两项。",
	"loging2.0_30":"一个私钥可以对应多个公钥，而每个公钥可以对应一个地址，地址是通过公钥进行一些数学逻辑变换转换而来，在交易对方知晓地址或者公钥时无法推算私钥，而知晓私钥，则可以推算公钥与地址。",
	"loging2.0_31":"交易发送者在发送交易时候，只需要提供公钥的签名即可完成交易的发出，或者资产的转移。",
	"loging2.0_32":"4.如果用户不慎遗失私钥，会有什么后果？",
	"loging2.0_33":"失去私钥，变等同于失去唯一凭证，私钥对应的地址内的所有资产将永久遗失，没有任何方法进行转移与交易。也无法通过任何外界手段进行资产的找回。",
	"loging2.0_34":"是的，可以通过ANT私钥安全中心进行找回。",
	"loging2.0_35":"5.若用户公开公钥，会不会有隐私泄露的问题？",
	"loging2.0_36":"可以在对应的“区块浏览器”上查询地址对应的持有人身份或者通过其他“人肉搜索”等手段获取用户的真实信息。",
	"loging2.0_37":"区块链具有“匿名性”特点，除用户公开承认和证明某个地址的私钥归自身所拥有，否则没有任何方式知晓持有地址资产的用户的真实信息。完全不需要担心隐私泄露问题。",
	"loging2.0_38":"提交答案",
	"loging2.0_39":"测试结果",
	"loging2.0_40":"恭喜您！成功通过测试。",
	"loging2.0_41":"开始创建新私钥",
	"loging2.0_42":"很遗憾！未能通过测试",
	"loging2.0_43":"继续学习",
	"loging2.0_44":"创建私钥",
	"loging2.0_45":"注意！密码用于保护私钥和交易授权，强度非常重要,AntToken不存储密码，也无法帮您找回，请务必牢记,密码必须要自己备份好。是用于加密保护私钥，强度也非常重要。",
	"loging2.0_46":"AntToken不存储密码，也无法帮您找回，请务必牢记",
	"loging2.0_47":"钱包名称：",
	"loging2.0_48":"密码：",
	"loging2.0_49":"确定密码：",
	"loging2.0_50":"我已仔细阅读并同意",
	"loging2.0_51":"服务及隐私条款",
	"loging2.0_52":"您已成功创建钱包，请及时备份私钥",
	"loging2.0_53":"建议使用抄写助记词方式进行备份,务必保证内容完全一致,并储放在安全的地方。",
	"loging2.0_54":"导出的Keystore文件内容请务必妥善存放",
	"loging2.0_55":"钱包名称",
	"loging2.0_56":"钱包地址:",
	"loging2.0_57":"助记词",
	"loging2.0_58":"复制",
	"loging2.0_59":"我已备份，进入钱包",
	"loging2.0_60":"备份钱包",
	"loging2.0_61":"提示",
	"loging2.0_62":"您是否确认已完成私钥备份并进入钱包",
	"loging2.0_63":"取消",
	"loging2.0_64":"确认",
	"loging2.0_65":"登录成功",
	"loging2.0_66":"私钥管理",
	"loging2.0_67":"修改钱包名字",
	"loging2.0_68":"修改密码",
	"loging2.0_69":"创建钱包",
	"loging2.0_70":"复制成功",
	"loging2.0_71":"导出私钥",
	"loging2.0_72":"导出Keystore",
	"loging2.0_73":"导出DSS Card",
	"loging2.0_74":"删除钱包",
	"loging2.0_75":"私钥密码",
	"loging2.0_76":"请输入来源地址对应的私钥密码",
	"loging2.0_77":"确认发送",
	"loging2.0_78":"当前私钥密码",
	"loging2.0_79":"新密码",
	"loging2.0_80":"重复新密码",
	"loging2.0_81":"安全警告：私钥未经加密，导出存在风险，建议使用助记词和Ketstore进行备份",
	"loging2.0_82":"删除成功",
	"loging2.0_83":"私钥密码错误",
	"loging2.0_84":"钱包名称不能为空",
	"loging2.0_85":"助记词",
	"loging2.0_86":"私钥",
	"loging2.0_87":"助记词，按空格分隔",
	"loging2.0_88":"开始导入",
	"loging2.0_89":"什么是助记词？",
	"loging2.0_90":"直接复制粘贴ANT官方钱包keystore文件内容至输入框。或者通过生成keystore内容的二维码，扫描录入",
	"loging2.0_91":"keystore文本内容",
	"loging2.0_92":"keystore密码：",
	"loging2.0_93":"什么是keystore？",
	"loging2.0_94":"明文私钥",
	"loging2.0_95":"什么是私钥？",
	"loging2.0_96":"钱包名称不能为空",
	"loging2.0_97":"钱包",
	"loging2.0_98":"充币",
	"loging2.0_99":"提币",
	"loging2.0_100":"明细",
	"loging2.0_101":"正在建设节点",
	"loging2.0_102":"正在获取...",
	"loging2.0_103":"可用余额",
	"loging2.0_104":"锁定余额",
	"loging2.0_105":"算力池(ANT)",
	"loging2.0_106":"锁仓总额",
	"loging2.0_107":"我的投入",
	"loging2.0_108":"我的合约",
	"loging2.0_109":"交易记录",
	"loging2.0_110":"充值地址",
	"loging2.0_111":"复制地址",
	"loging2.0_112":"注意事项：",
	"loging2.0_113":"&nbsp;1.需要12个网络确认才能到账,任何非ETH资产充值到ETH地<br/>&nbsp;址后不可找回,充值最小额度为1ETH,小于1ETH将无法到账！",
	"loging2.0_114":"&nbsp;2.您的充值地址相当于您的银行账号,如果您想进行数字资产<br/>&nbsp;的转移,您只需提供该地址给对方即可。",
	"loging2.0_115":"签约",
	"loging2.0_116":"提币地址",
	"loging2.0_117":"提币数量",
	"loging2.0_118":"当前可用",
	"loging2.0_119":"支持金额：最低提币金额为1ETH。",
	"loging2.0_120":"提现限制：您的24H提币额度为10000ETH。",
	"loging2.0_121":"提现矿工费：根据您所选择消耗的矿工费快慢不同而不同。",
	"loging2.0_122":"提币地址：您的提币地址即您交易平台账号的充币地址，每个交易平台中的每个币种都对应一个地址；要把您的资产从钱包提到交易平台，您只需填写对应交易平台的对应币种的充币地址即可。",
	"loging2.0_123":"提币确认",
	"loging2.0_124":"矿工费",
	"loging2.0_125":"确认提币",
	"loging2.0_126":"提取全部",
	"loging2.0_128":"预计1小时内完成交易",
	"loging2.0_129":"慢",
	"loging2.0_130":"正常",
	"loging2.0_131":"快",
	"loging2.0_132":"签约挖矿",
	"loging2.0_133":"签约数量",
	"loging2.0_134":"签约对象",
	"loging2.0_135":"全部签约",
	"loging2.0_136":"签订合约",
	"loging2.0_137":"数量限制：单次签约数量应当大于等于100ANT。",
	"loging2.0_138":"关于提取：本金任意时间可提。",
	"loging2.0_139":"矿工费：根据您所选择消耗的矿工费快慢不同而不同。",
	"loging2.0_140":"签约对象：指您想要参与的挖矿币种，选择币种签约后即可参与对应币种挖矿；当前仅支持ANT挖矿，后续将加入各主流可挖矿币种的挖矿活动。",
	"loging2.0_141":"我的合约",
	"loging2.0_142":"算力合约",
	"loging2.0_143":"众筹合约",
	"loging2.0_144":"全部",
	"loging2.0_145":"一键解约",
	"loging2.0_146":"一键领取",
	"loging2.0_147":"全部",
	"loging2.0_148":"预热中",
	"loging2.0_149":"进行中",
	"loging2.0_150":"已结束",
	"loging2.0_151":"我的记录",
	"loging2.0_152":"每个ID限购10000枚",
	"loging2.0_153":"签约确认",
	"loging2.0_154":"预热中",
	"loging2.0_155":"进行中",
	"loging2.0_156":"已结束",
	"loging2.0_157":"我的记录",
	"loging2.0_158":"众筹记录",
	"loging2.0_159":"类型",
	"loging2.0_160":"众筹数量",
	"loging2.0_161":"日期",
	"loging2.0_162":"金额",
	"loging2.0_163":"项目详情",
	"loging2.0_164":"ANT蚂蚁通证",
	"loging2.0_165":"总量(ANT)",
	"loging2.0_166":"已参与(ANT)",
	"loging2.0_167":"剩余天数",
	"loging2.0_168":"项目介绍",
	"loging2.0_169":"白皮书",
	"loging2.0_170":"请输入购买数量",
	"loging2.0_171":"枚",
	"loging2.0_172":"立即购买",
	"loging2.0_173":"更改密码",
	"loging2.0_174":"当前私钥密码",
	"loging2.0_175":"新密码",
	"loging2.0_176":"重复新密码",
	"loging2.0_177":"合约",
	"loging2.0_178":"扫码下载我们的APP",
	"loging2.0_179":"邀您一起打造全球商业大联盟",
	"loging2.0_180":"我的邀请码",
	"loging2.0_181":"&nbsp;&nbsp;&nbsp;&nbsp;ANT Token即蚂蚁通证，立足于服务实体经济、为传统行业赋能，利用通证将商户和用户连接在一起，形成一个商业大联盟，告别单打独斗，孤军奋战的时代。ANT致力于创建一个安全、高效、透明的通证经济应用系统，让商户和用户形成一个利益共同体，最终实现商户产品不愁卖，用户购买产品有折扣还能享受商户权益分红的互惠互利，共享共赢模式。ANT是一个所有ANT Token持有者和联盟商户共有、共治、共享的社区型组织。<br />&nbsp;&nbsp;&nbsp;&nbsp;ANT基金会于2018年9月1日发起，于9月5日向新加坡相关部门提交项目白皮书和非证券化证明以及私募公募条款等相关资料，并于12月3日正式通过审核，由此宣告成立的非盈利性机构。<br />&nbsp;&nbsp;&nbsp;&nbsp;ANT基金会致力于打造全球商业大联盟，开启双通证经济，为实体产业赋能。<br />&nbsp;&nbsp;&nbsp;&nbsp;ANT Token：服务于实体经济，是区块链技术落地的权益证明，致力于帮助商户产品不愁卖，消费者无痛消费的新经济体系。<br />&nbsp;&nbsp;&nbsp;&nbsp;ANT Coin：专注区块链技术研发，致力于解决区块链链上转账速度慢，算力垄断，储存不便、交易繁琐、落地难等问题。ANT Coin主链以权益挖矿和主节点分配方式，恒量发行50亿枚，其中39%（19.5亿枚）创世块预挖通过招募联合创始人分三期发行。剩余部分以pos挖矿和主节点挖矿产出。",
	"loging2.0_182":"关于我们",
	"loging2.0_183":"请设置钱包名称",
	"loging2.0_184":"不少于8位字符，建议混合大小字母和数字",
	"loging2.0_185":"请再次输入密码",
	"loging2.0_186":"导出助记词",
	"loging2.0_187":"离线保存",
	"loging2.0_188":"请复制粘贴keystore文件到安全、离线的地方保存。请勿保存至邮箱、记事本、网盘导航聊天工具等，非常危险。",
	"loging2.0_189":"请勿使用网络传输",
	"loging2.0_190":"请勿通过网络工具传输Keystore文件，一旦被黑客获取将造成不可挽回的资产损失。",
	"loging2.0_191":"密码保险箱保存",
	"loging2.0_192":"如需在线保存，则建议使用安全等级更高的密码保管软件来保存Keystore。",
	"loging2.0_193":"复制Keystore",
	"loging2.0_194":"发送成功",
	"loging2.0_195":"金额不符合",
	"loging2.0_196":"个数不符合",
	"loging2.0_197":"私钥密码错误",
	"loging2.0_198":"输入内容有空",
	"loging2.0_199":"商城",
	"loging2.0_200":"燃烧",
	"loging2.0_201":"私钥密码错误",
	"loging2.0_202":"留言",
	"loging2.0_203":"存入资产",
	"loging2.0_204":"暂未开放",
	"loging2.0_205":"众筹",
	"loging2.0_206":"交易记录",
	"loging2.0_207":"我的锁仓",
	"loging2.0_208":"官网",
	"loging2.0_209":"白皮书",
	"loging2.0_210":"浏览器",
	"loging2.0_211":"RUB服务",
	"loging2.0_212":"当前汇率≈",
	"loging2.0_213":"参与众筹",
	"loging2.0_214":"众筹规则",
	"loging2.0_215":"最近众筹",
	"loging2.0_216":"等待中",
	"loging2.0_217":"已完成",
	"loging2.0_218":"上拉显示更多",
	"loging2.0_219":"正在加载",
	"loging2.0_220":"已经全部加载完了",
	"loging2.0_221":"下拉可以刷新",
	"loging2.0_222":"释放立即刷新",
	"loging2.0_223":"正在刷新",
	"loging2.0_224":"众筹规则:",
	"loging2.0_225":"众筹是采用跨链交易技术，实现不同数字资产之间的自由快速兑换。众筹会在区块链的智能合约上完成交换，无需信任第三方。",
	"loging2.0_226":"众筹比例:",
	"loging2.0_227":"众筹的比例由后端服务器从区块链智能合约上实时获取。",
	"loging2.0_228":"成交规则:",
	"loging2.0_229":"提交众筹订单后，会广播至以太坊和兑换对象的区块链网络等待矿工打包。众筹成功之后你将在众筹记录里看到这笔订单的记录。",
	"loging2.0_230":"参与众筹",
	"loging2.0_231":"详情(RUB)",
	"loging2.0_232":"支付金额:",
	"loging2.0_233":"换取金额:",
	"loging2.0_234":"付款地址:",
	"loging2.0_235":"收款地址:",
	"loging2.0_236":"交易号:",
	"loging2.0_237":"已确认",
	"loging2.0_238":"我的锁仓(RUB)",
	"loging2.0_239":"释放时间:",
	"loging2.0_240":"锁仓数量:",
	"loging2.0_241":"已释放总额:",
	"loging2.0_242":"交易号:",
	"loging2.0_243":"可提取RUB",
	"loging2.0_244":"领取收益",
	"loging2.0_245":"推荐码",
	"loging2.0_246":"语言设置",
	"loging2.0_247":"兑换",
	"loging2.0_248":"认购",
	"loging2.0_249":"参与认购",
	"loging2.0_250":"认购规则",
	"loging2.0_251":"最近认购",
	"loging2.0_252":"认购确认",
	"loging2.0_253":"兑换RUB规则:",
	"loging2.0_254":"每个ANT账号根据资产数量按比例获得相应兑换限额；<br />资产越多兑换RUB的个数就越多。",
	"loging2.0_255":"兑换比例:",
	"loging2.0_256":"1个A通证=1 CNY<br />按照实时RUB的价格进行换算",
	"loging2.0_257":"兑换锁仓:",
	"loging2.0_258":"自RUB上线交易平台开始计算锁仓时间；<br />锁仓10个月，每个月释放10%。<br />注：每一个账号需要0.1ETH激活兑换功能。",
	"loging2.0_259":"兑换限额:",
	"loging2.0_260":"每个账号兑换限额：不超过50万枚；<br />平台总兑换限额：不超过5亿枚。",
	"loging2.0_261":"抱歉,ANT正在努力建设中<br/>请您耐心等待~",
	"loging2.0_262":"ANT通兑换WBC商城积分规则:",
	"loging2.0_263":"首期兑换时间:9月30日 10:00–10月6日23:59<br/>每个ANT账号都可用ANT通证或资产按比例兑换WBC商城积分",
	"loging2.0_264":"兑换比例:",
	"loging2.0_265":"1ANT通证=1商城积分<br/>6资产=1商城积分",
	"loging2.0_266":"该认购已结束",
	"loging2.0_267":"兑换数量:",
	"loging2.0_268":"每个账号兑换限额:不超过5万个<br/>首期可兑换总限额:不超过5亿个",
	"loging2.0_269":"本轮剩余兑换量:",
	"loging2.0_270":"绑定地址",
	"loging2.0_271":"本地已有Ruby钱包",
	"loging2.0_272":"正在安装，请返回桌面查看安装状态",
	"loging2.0_273":"立即信任",
	"loging2.0_274":"请等待下载结束,进行钱包绑定",
	"loging2.0_275":"钱包地址不得为空",
	"loging2.0_276":"立即绑定",
	"loging2.0_277":"请输入钱包地址",
	"loging2.0_278":"Ruby钱包地址",
	"loging2.0_279":"当前功能需要跳转Ruby App",
	"loging2.0_280":"如未下载，请先下载安装",
	"loging2.0_281":"立即下载",
}

var EN={
	"Reward1":"Reward",
	"Login":'Login',//登录页
	"Register":'Register',
	"Forgot":'Forgot',
	"Mobile":"Mobile:",
	"Password":"Password:",
	"EnterMobile":"Enter Mobile",
	"EnterPassword":"Enter Password",
	"ReferralID":"Referral ID:",
	"EnterreferralID":"Enter referral ID",
	"Next":"Next",
	"Verifycode":"Verify code：",
	"SendSMS":"Send SMS",
	"EnterSMS":"Enter SMS",
	"ConfirmPassword":"Confirm Password：",
	"Confirmloginpassword":"Confirm login password：",
	"PaymentPassword":"Payment Password：",
	"CreatePaymentpassword":"Create Payment password：",
	"ConfirmPaymentpassword":"Confirm Payment password：",
	"Finish":"Finish",
	"CreatenewPassword":"Create new Password:",
	"EnternewPassword":"Enter new Password",
	"ConfirmnewPassword":"Confirm new Password:",
	"EnterrepeatnewPassword":"Enter repeat new Password",
	"indexTransfer":"Transfer",//首页
	"ReceiptCode":"Receipt Code",
	"Reward":"Reward",
	"Token":"Token",
	"History":"History",
	"Asset":"Asset",
	"Convert":"Convert",
	"TokenService":"Token Service",
	"Activatefriend":"Activate friend",
	"Node":"Node",
	"Invitationcard":"Invitationcard",
	"Contract":"Contract",
	"POS":"POS",
	"DPOS":"DPOS",
	"LifeService":"Life Service",
	"Help":"Help",
	"FuelCard":"Welfare Draw",
	"Booking":"Booking",
	"ANTcloudpurchase":"Cloud Purchase",
	"Dripping":"Dripping",
	"Game":"Game",
	"Takeaway":"Takeaway",
	"Information":"Information",
	"More":"More",
	"Home":"Home",
	"Wallet":"Wallet",
	"Trades":"Trades",
	"Mall":"Mall",
	"Receipt Code1":"Receipt Code",
	"Invitationcard":"Invitation card",//侧边栏
	"IdentityAuthentication":"Identity Authentication",
	"Security":"Security",
	"Message":"Message",
	"Versiondetection":"Version detection",
	"Aboutus":"About us",
	"Settings":"Settings",
	"Logout":"Logout",
	"Transfer":"Transfer",//转账
	"Choosetransfermethod":"请选择转账方式",
	"Directtransfer":"直接转账",
	"Scantotransfer":"扫码转账",
	"Callprefix":"Callprefix：",
	"Transferredaccount":"Acct No：",
	"Fillinthetransferaccount":"Fill in the transfer account",
	"Pleaseconfirmthattheaccountiscorrectandavoidtheloss":"Please reconfirm your account and avoid loss",
	"Transfercoins":"Transfer coins：",
	"Quantitytransferred":"QTY：",
	"AvailableToken":"Available Token：",
	"Fee":"Fee：",
	"Actualtransfer":"Actualtransfer：",
	"Transactionconfirmation":"Transaction confirmation",
	"History1":"History",
	"Transferredaccount1":"Acct No",
	"Enternickname":"Enter nickname",
	"Theusername":"The user name",
	"Transferamount":"Transfer amount",
	"SelectCoin":"Select Coin",
	"Latestarrivaltime":"Latest arrival time:",
	"Estimatedarrivaltime":"Estimated arrival time",
	"Thenextdaybeforearrives":"The next day before 24:00 arrives",
	"Confirm":"Confirm",
	"Cancel":"Cancel",
	"Enterpaymentpassword":"Enter payment password",
	"Forgottopaymentpassword":"Forgot to payment password",
	"Pleasewait":"Pleasewait...",
	"Burning":"Burning",
	"Transactioncreation":"Transaction creation",
	"InformationCollection":"Information Collection",
	"TransactionEncryption":"Transaction Encryption",
	"SafetyVerification":"Safety Verification",
	"SendTheTransactionRequest":"Send The Transaction Request",
	"Success":"Success",
	"Pass":"Pass",
	"CLR":"CLR",
	"DEL":"DEL",
	"Transresult":"Transresult",
	"SFA":"SFA",
	"CFM":"CFM",
	"Remarks：":"Remarks：",
	"Remarks":"Remarks",
	"Fill Remarks":"Fill Remarks",
	"ReceiptCode":"Receipt Code",//收款码
	"SweeptheQRcodeonthetopandtransfertoeachother":"Sweep the QR code on the top and transfer to each other",
	"nickname666":"Name:",
	"Accounts666":"Phone:",
	"Sweep to transfer money to me":"Scan transfers money to me",
	"Save to album":"SAVE TO ALBUM",
	"Assetshistory":"Assets history",//资产详情
	"Assetcomposition":"Asset composition",
	"AvailableToken":"Available Token",
	"Assets":"Assets",
	"Converttoassets":"Convert to assets",
	"History2":"History",
	"Transferout":"Transfer out",
	"Transfer":"Transfer",
	"Converttoassets1":"Convert toassets",//兑换资产
	"Tokens":"Tokens",
	"Convertquantity":"Convert quantity",
	"Enterquantity":"Enter quantity",
	"Afterconvert":"After convert",
	"Communityfriends":"Community friends",//社区好友
	"Numberofinvitations":"Number of invitations：",
	"Nickname1":"Nickname",
	"Username":"Username",
	"Status":"Status",
	"Pleasechoosethedistributionmethod":"Please choose the distribution method",
	"Defaultallocationnode":"Default allocation node",
	"Manuallyassignnodes":"Manually assign nodes",
	"Areyousureassigndefaultcontacts":"Are you sure assign default contacts",
	"Confirm":"Confirm",
	"Cancel":"Cancel",
	"Bindingcontact":"Binding contact",
	"Contactmark":"Contact mark",
	"Entercontactmark":"Enter contact mark",
	"Nodeinformation":"Contact information",
	"Search":"Search",
	"Pleaseconfirm":"Please confirm that the contact information is correct and cannot be modified once activated",
	"Confirmactivationoffriends":"Confirm activation of friends",
	"MyNode":"My Node",//我的节点
	"T1Node":"T1 Node",
	"Nodereward":"Node reward>>",
	"Assets1":"Assets:",
	"Numberofnodes":"Num of nodes:",
	"Referee":"Referee:",
	"T2Node":"T2 Node",
	"Nodereward1":"Node reward",//节点奖励
	"YesterdayTokenreward":"Yesterday Token reward",
	"CumulativeTokenreward":"Cumulative Token reward",
	"Yesterdayassetaward":"Yester dayasset award",
	"Cumulativeassetaward":"Cumulative asset award",
	"Noderewarddescription":"Node reward description",
	"Recentnodereward":"Recent node reward",
	"Reward":"Reward",
	"Invitationcard":"Invitation card",//邀请卡
	"InviteFriends":"Invite Friends",
	"ReferralID1":"Referral ID",
	"ScanQRcode":"Scan QR code",
	"RegistertheANTaccount":"Register the ANT account",
	"Posdescription":"Pos description",//POS
	"RecentPos":"Recent Pos",
	"DPOSdescription":"DPOS description",//DPOS
	"Todayassetaward":"Today asset award",
	"Tokenrewardtoday":"Token reward today",
	"RecentDPOS":"Recent DPOS",
	"Accountlock":"Account lock",//安全中心
	"Openprotectedaccountisnothacked":"Open protected account is not hacked",
	"Regionallock":"Regional lock",
	"Openthegeographicalmodetoprotecttheaccountfrombeinghacked":"Open area mode to protect the account is not hacking",
	"Pattern":"Pattern",
	"OpenwhenAPPislocked":"Open when APP is locked",
	"ChangeLoginpassword":"Change Login password",
	"Usedforaccountlogin":"Used for account login",
	"ChangePaymentpassword":"Change Payment password",
	"Usewhenchangingaccountfunds":"Use when changing account funds",
	"Changephonenumber":"Change phone number",
	"Changetheoriginalboundphonenumber":"Change the original bound phone number",
	"Changepaymentpassword":"Change payment password",
	"Usewhenchanging account funds":"Use when changing account funds",
	"E-mailsecurity":"E-mail security",
	"ChangetheoriginalboundE-mail":"Change the original bound E-mail",
	"ChangeLoginPassword":"Change Login Password",//修改登录密码
	"Enteroldpassword":"old password",
	"Enteroldpassword1":"old password：",
	"Enternewpassword":"new password",
	"Enternewpassword1":"new password：",
	"ConfirmNewPassword":"Confirm Password",
	"ConfirmNewPassword1":"Confirm Password：",
	"Submit":"Submit",
	"ChangePaymentpassword":"Change Payment password",//修改支付密码
	"Changephonenumber":"Change phone number",//修改手机认证
	"Newphonenumber":"New phone：",
	"Newcallprefix":"New call prefix：",
	"Paymentpassword":"Payment password：",
	"Confirmagain":"Confirm again",
	"Enteranewpaymentpassword":"new payment password",
	"Walletassetsvalue":"Wallet assets value",//钱包
	"Deposit":"Deposit",
	"Withdrawal":"Withdrawal",
	"History":"History",
	"Assethistory":"Asset history",
	"Frozen":"Frozen",
	"Buy":"Buy",//交易
	"Sell":"Sell",
	"Crowd-funding":"ICO",
	"Transactionservice":"Transaction service",
	"Orders":"Orders",
	"Trading":"Trading",
	"OK":"Completed",
	"Orderhistory":"Order history",
	"Creditrecord":"Credit record",
	"Workorder":"Work order",
	"Bankcard":"Bank card",
	"Complaints&Suggestions":"Feedbacks",
	"Mallentrance":"Mall entrance",//商城
	"Buildingaglobalbusinessalliance":"Building a global business alliance",//联系客服
	"CSR(WeChat)":"ANT-CSR(WeChat)：",
	"CSR(QQ)":"MALL-CSR(WeChat)：",
	"CSR(QQ)01":"ANT-CSR(QQ)：",
	"Copy":"Copy",
	"VIP":"VIP",
	"AllCategories":"All Categories",
	"WelcomeToANTMall":"Welcome To ANT Mall",
	"TransactionDetails":"Transaction Details",//交易详情
	"Orderinformation":"Order information",
	"Ordernumber":"Order number",
	"Typeoftransaction":"Type of transaction",
	"Transactiontime":"Transaction time",
	"Disburserinformation":"Disburser information",
	"Spendingaccount":"Spending account",
	"Accountnickname":"Account nickname",
	"Coins":"Coins",
	"Fee1":"Fee",
	"Tokenchange":"Token change",
	"Assetchange":"Asset change",
	"Payeeinformation":"Payee information",
	"Receivingaccount":"Receiving account",
	"Receiverinformation":"Receiver information",
	"History3":"History",
	"Detailsoffriends":"Details of friends",//好友详情
	"Friendinformation":"Friend information：",
	"Contactperson":"Contact：",
	"return":"back",//国家选择
	"Choosethecountry":"Choose the country",
	"rewarddescription":"reward description",//奖励说明
	"(Currentversion)":"(Current version)",//版本检测
	"VersionInformation":"Version Information",
	"Latestversion":"Latest version",
	"Releasetime":"Release time",
	"Installationpackagesize":"Installation package size",
	"Updatecontent":"Update content",
	"Contract Scratch":"Happy New Year",//合约刮刮
	"Rule Of Activity":"Rule Of Activity",
	"1101":"Happy New Year: New Year's Day stockpiling, the Fortune is you.ANT contract scratch since its launch, the market reaction unprecedented warm.In response to strong demand of the general membership, also congratulated the ANT MALL grand opening,ANT Fortune swept struck, benefits continue to pass!500,000 ANT Token waiting for you to collect, to help New Year's Day hoarding goods!Your New Year's Goods, ANT help you hoard!",
	"1102":"All ANT registered members,Participate once consumed 100ANT(All participants receive 100 asset awards, which is equivalent to free participation),Starting at 12 noon on January 1, 2019,Limited to 5000 sheets, first come first served, while stocks last.",
	"Award Setting：":"Award Setting：",
	"First prize 2 places:50000ANT":"First prize 2 places:50000ANT",
	"Second prize 10 places:10000ANT":"Second prize 10 places:10000ANT",
	"Third prize 100 places:1000ANT":"Third prize 100 places:1000ANT",
	"Fourth prize 500 places:200ANT":"Fourth prize 1000 places:200ANT",
	"All participants receive 100 asset awards":"All participants receive 100 asset awards",
	"Note: The final interpretation of this activity belongs to ANT Team":"Note: The final interpretation of this activity belongs to ANT Foundation.",
	"Receive":"Receive",
	"Come again":"Come again",
	"Exit":"Exit",
	"History03":"History",
	"Winning":"Winning",
	"Congratulations Lucky prize":"Congratulations Lucky prize",
	"Congratulations 1st prize":"Congratulations 1st prize",
	"Congratulations 2nd prize":"Congratulations 2nd prize",
	"Congratulations 3rd prize":"Congratulations 3rd prize",
	"Congratulations 4th prize":"Congratulations 4th prize",
	"Lucky prize":"Lucky prize",
	"1st prize":"1st prize",
	"2nd prize":"2nd prize",
	"3rd prize":"3rd prize",
	"4th prize":"4th prize",
	"Deposit in wallet":"Deposit in wallet",
	"Scratch history":"Scratch history",
	"Winning user":"Winning user",
	"Winning result":"Result",
	"Scratch rewards":"Scratch rewards",
	"Date":"Date",
	"Welfare Draw":"Welfare Draw",//福利大转盘
	"The number of draws currently held":"frequency：",
	"Thank you":"Thank you",
	"Welfare Draw":"Welfare Draw",
	"Winning history":"Winning history>>",
	"Activity description":"Activity description",
	"1Assets":"1Assets",
	"10Assets":"10Assets",
	"100Assets":"100Assets",
	"1000Assets":"1000Assets",
	"10000Assets":"10000Assets",
	"100000Assets":"100000Assets",
	"WelfareText":"Since ANT has been on the line,in just a few months,the number of members has exploded.Thanks to the support and love of ANT and old members,ANT has launched Welfare Draw to thank the new and old members.During the event,each time a valid friend is invited,and a new registered valid user will receive 1 free lucky draw chance.Up to 100,000 assets waiting for you to come,what are you waiting for,and invite friends to come to the lucky draw!",
	"WelfareText1":"Note: A valid user means to convert the pass to more than 100 assets.",
	"WelfareText2":"The final interpretation of this event belongs to ANT.",
	"Winning history1":"Winning history",
	"Announcement":"Announcement",//通知公告
	"Fill in business information":"Fill in business information",//商户收款码
	"Collection account:":"Collection account:",
	"Product name:":"Product name:",
	"Unit Price:":"Unit Price:",
	"Mobile phone:":"Mobile phone:",
	"Product Description:":"Product Description:",
	"Generate a color QR code":"Generate a receipt QR code",
	"Generate a monochrome QR code":"Generate a monochrome QR code",
	"Product Description":"Product Description",
	"Save to phone album":"Save to phone album",
	"Lucky red packet":"Lucky red packet",//锦鲤红包
	"History of red packets":"History of red packets",
	"Shake":"Shake",
	"Grab the asset red packet":"Grab the asset red packet",
	"Distribute red packets":"Distribute red packets",
	"Red packet type":"Red packet type",
	"Ordinary red packet":"Ordinary red packet",
	"RedAmounts":"RedAmounts",
	"Please enter the amounts":"Please enter the amounts",
	"Friend account":"Friend account",
	"Friends Mobile Number":"Friends Mobile Number",
	"Messages":"Messages",
	"Good fortune":"Good fortune",
	"Confirm send":"Confirm send",
	"Amount or number of red packets not filled in":"Amount or number of red packets not filled in",
	"Amount does not match":"Amount does not match",
	"RedNumber":"RedNumber",
	"Please enter the number":"Please enter the number",
	"Sending mode":"Sending mode",
	"Fixed amount":"Fixed amount",
	"Random amount":"Random amount",
	"Selection area":"Selection area",
	"Ordinary red packet1":"Ordinary red packet",
	"Area red packet":"Area red packet",
	"Area red packet1":"Area red packet",
	"Congratulations on receiving a red packet of assets":"Congratulations on receiving a red packet of assets",
	"Valid on the day":"Valid on the day",
	"Congratulations on receiving the asset red packet":"Congratulations on receiving the asset red packet",
	"Deposit into assets":"Deposit into assets",
	"My red packet":"My red packet",
	"Friends":"Friends",
	"Add":"Add",
	"Mobile5":"Mobile",
	"RedEnvelopeTitle":"Activity Description：",
	"RedEnvelopeText1":"With the arrival of Chinese traditional Spring Festival, the function of ANT red packet is officially launched!",
	"RedEnvelopeText2":"Partners can use their assets to send red packet to relatives and friends, send wishes and bring good luck!",
	"RedEnvelopeText3":"This year's Festival does not accept gifts, only accept ANT.",
	"RedEnvelopeText4":"Regional red packet: Select a province, city, region, input the number of assets, click Send to let all members of the region through ANT shake to receive your blessing red packet.The sending areared packet is limited to 2000 assets each time, and the maximum daily delivery is no more than 10,000 assets; the regional red packet is not more than 2000 assets per day.",
	"RedEnvelopeText5":"Ordinary red packet: After entering the ANT account of relatives and friends, input the amount of assets, you can send blessings and good luck to relatives and friends in the form of red packet.A single ordinary red packet cannot exceed 100 assets, and the upper limit is 1000 assets per day; the ordinary red packet cannot exceed 1000 assets per day.",
	"RedEnvelopeText6":"Activity Description",
	//2.0版本文案
	"loging2.0_1":"Forget password",
	"loging2.0_2":"Private key login",
	"loging2.0_3":"Register",
	"loging2.0_4":"Import private key",
	"loging2.0_5":"Account password",
	"loging2.0_6":"Private Key Security Classroom",
	"loging2.0_7":"For the sake of your asset security, please read the following agreements carefully!",
	"loging2.0_8":"Private keys are the entrance to a digital wallet. Only private keys can prove that you are the owner of the assets in the wallet, and no one knows these private keys except you. This is the biggest difference between de-centralization and centralization. Your digital assets are under your own control and there is no centralized institution involved.",
	"loging2.0_9":"Private key is a 32-byte random number generated by the Elliptic Curve Encryption algorithm. It consists of 64 hexadecimal characters, and a wallet has only one private key, which can not be modified. It is your only identity certificate on the chain. A private key can correspond to multiple public keys, and each public key can correspond to an address, which is changed by some mathematical logic through the public key. Conversely, it is impossible to deduce the private key when the address or public key is known, but when the private key is known, the public key and address can be deduced.",
	"loging2.0_10":"Block chains have the characteristics of 'anonymity'. There is no way to know the real information of the user who holds the address assets except that the user publicly acknowledges and proves that the private key of an address belongs to himself. There is absolutely no need to worry about privacy disclosure.",
	"loging2.0_11":"Mnemonic words are usually composed of 12 random words, in other words, mnemonic words are another form of private key. It converts 64-bit private keys into several common English words or vocabulary versions in other languages through algorithms.",
	"loging2.0_12":"You can understand mnemonics as different forms of private keys, need backup, and try to record them with paper notes when backing up. You can let your family keep one, keep one by themselves, don't save it on the network, such as cloud notes, chat records, etc. If you change your mobile phone, you can restore your wallet by backing up. You can import your wallet through mnemonics, but conversely, if someone else gets your mnemonics, you can transfer your assets, so keep your mnemonics properly.",
	"loging2.0_13":"If the private key loses or forgets the private key password, without backup mnemonics, it is equivalent to losing the only credentials. All assets in the address corresponding to the private key will be lost permanently. There is no way to transfer and trade, nor can assets be recovered by any external means.",
	"loging2.0_14":'Plaintext Private Key: 64-bit hexadecimal hash value string, with a sentence to illustrate the importance of plaintext private key: "Who has the private key, who has the right to use the wallet!"',
	"loging2.0_15":"The world of block chain is still a little different from reality. For example, if you forget your bank card password, you can take your ID card to the bank and reset the password yourself. And the private key of the digital wallet, you forgot, and there is no backup mnemonic, then nobody can help you, contact customer service, provide mobile phone authentication code, wallet address and so on can not be retrieved, because this is a decentralized DAPP, will not store the user's private key, all private keys are stored only in the user's local.",
	"loging2.0_16":"You can test it on the same phone, or you can test it on another phone to verify that the backup is correct.",
	"loging2.0_17":"The same mobile phone import, if the original wallet exists, will tell you that the wallet already exists, indicating that the backup is correct.",
	"loging2.0_18":"Different mobile phone imports, can be imported successfully, although the name is different, but the address is the same, the instructions are also noted right.",
	"loging2.0_19":"I have read and understood the protocol and am willing to follow it.",
	"loging2.0_20":"Next, start the test.",
	"loging2.0_21":"Private key security test",
	"loging2.0_22":"1. The private key is your only identity certificate on the chain. If the private key loses or forgets the private  key password, it will not be retrieved in any way.",
	"loging2.0_23":'Private keys are generated by "elliptic curve encryption algorithm" with the computing power of ordinary  computers. If the private keys are lost, they will not be retrieved.',
	"loging2.0_24":"After the loss, you can use the mobile phone number and verification code to retrieve.",
	"loging2.0_25":"2. The private key created in ANT Token can be retrieved by contacting customer service, providing mobile phone number,  verification code and wallet address if I accidentally lose it?",
	"loging2.0_26":'Unable to retrieve, all the private keys used in ANT Token are computed from the devices used in user  generation. As a "de-centralized" app, ANT Token does not backup any user s private keys.',
	"loging2.0_27":"Yes, it can be retrieved through the ANT Private Key Security Center.",
	"loging2.0_28":"3. Is the conceptual description between private key, public key and address correct?",
	"loging2.0_29":"Private key, public key and address can be converted at will. If one of them is known, the other two can be deduced.",
	"loging2.0_30":"A private key can correspond to multiple public keys, and each public key can correspond to an address. The address is converted by some mathematical logic transformation of the public key. When the other party knows the address or the public key, the private key and the address can not be deduced. If the other party knows the private key, the public key and the address can be deduced.",
	"loging2.0_31":"When sending a transaction, the sender only needs to provide the signature of the public key to complete the issue of the transaction or the transfer of assets.",
	"loging2.0_32":"4. What will happen if the user accidentally loses his private key?",
	"loging2.0_33":"Losing the private key becomes equivalent to losing the unique credentials. All assets in the address corresponding to the private key will be lost permanently. There is no way to transfer and trade. Nor can assets be recovered by any external means.",
	"loging2.0_34":"Without any consequences, a new private key and address can be generated and the assets can be transferred.",
	"loging2.0_35":"5. If the user publishes the public key, will there be any privacy leak?",
	"loging2.0_36":'It can query the identity of the holder corresponding to the address on the corresponding "block browser" or obtain the real information of the user through other means such as "human flesh search".',
	"loging2.0_37":"Block chains have the characteristics of 'anonymity'. There is no way to know the real information of the user who holds the address assets except that the user publicly acknowledges and proves that the private key of an address belongs to himself. There is absolutely no need to worry about privacy disclosure.",
	"loging2.0_38":"Submit answers",
	"loging2.0_39":"Test Result",
	"loging2.0_40":"Congratulations! Successfully passed the test.",
	"loging2.0_41":"Start creating a new private key",
	"loging2.0_42":"Unfortunately! Failed to pass the test",
	"loging2.0_43":"Continue learning",
	"loging2.0_44":"Create a private key",
	"loging2.0_45":"Be careful! Passwords are used to protect private keys and transaction authorization. Strength is very important. ANT does not store passwords, nor can it help you retrieve them. Please bear in mind that passwords must be backed up by themselves. It is used to encrypt and protect private keys. Strength is also very important.",
	"loging2.0_46":"·ANT Token does not store passwords, nor can it help you find them. Please remember",
	"loging2.0_47":"Name of wallet:",
	"loging2.0_48":"Password:",
	"loging2.0_49":"Confirm password",
	"loging2.0_50":"I have read it carefully and agreed.",
	"loging2.0_51":"Service and Privacy Provisions",
	"loging2.0_52":"You have successfully created your wallet. Please backup your private key in time.",
	"loging2.0_53":"It is recommended to use copying mnemonics for backup, so as to ensure that the contents are identical and stored in a safe place.",
	"loging2.0_54":"· The contents of exported Keystore files must be stored properly",
	"loging2.0_55":"Wallet",
	"loging2.0_56":"Wallet Address:",
	"loging2.0_57":"Mnemonic word",
	"loging2.0_58":"Copy",
	"loging2.0_59":"I backed it up and went into my wallet.",
	"loging2.0_60":"Backup Wallet",
	"loging2.0_61":"Tips",
	"loging2.0_62":"Do you confirm that you have completed the private key backup and entered your wallet?",
	"loging2.0_63":"Cancel",
	"loging2.0_64":"Confirm",
	"loging2.0_65":"Login successfully",
	"loging2.0_66":"Private key management",
	"loging2.0_67":"Change the name of the wallet",
	"loging2.0_68":"Change Password",
	"loging2.0_69":"Create Wallet",
	"loging2.0_70":"Successful copy",
	"loging2.0_71":"Export private key",
	"loging2.0_72":"Export Keystore",
	"loging2.0_73":"Export DSS Card",
	"loging2.0_74":"Delete wallet",
	"loging2.0_75":"Private key password",
	"loging2.0_76":"Enter the private key password corresponding to the source address",
	"loging2.0_77":"Confirm send",
	"loging2.0_78":"Current Private Key Password",
	"loging2.0_79":"New password",
	"loging2.0_80":"Confirm again",
	"loging2.0_81":"Security Warning: Private keys are not encrypted and exporting is risky. It is recommended to use mnemonics and Ketstore for backup.",
	"loging2.0_82":"successfully deleted",
	"loging2.0_83":"Private key password error",
	"loging2.0_84":"Wallet name cannot be empty",
	"loging2.0_85":"Mnemonic",
	"loging2.0_86":"Private key",
	"loging2.0_87":"Mnemonic words, separated by spaces",
	"loging2.0_88":"Start importing",
	"loging2.0_89":"What is Mnemonic word?",
	"loging2.0_90":"Copy and paste the contents of the ANT official wallet keystore file directly into the input box. Or by generating two-dimensional codes of keystore content, scan and enter",
	"loging2.0_91":"Keystore text content",
	"loging2.0_92":"Keystore password:",
	"loging2.0_93":"What is keystore？",
	"loging2.0_94":"Plaintext private key",
	"loging2.0_95":"What is a private key?",
	"loging2.0_96":"钱包名称不能为空",
	"loging2.0_97":"Wallet",
	"loging2.0_98":"Deposit",
	"loging2.0_99":"Withdrawal",
	"loging2.0_100":"History",
	"loging2.0_101":"Under construction node",
	"loging2.0_102":"Fetching...",
	"loging2.0_103":"Available Balance",
	"loging2.0_104":"Lock balance",
	"loging2.0_105":"Computing pool(ANT)",
	"loging2.0_106":"Total lock position",
	"loging2.0_107":"My input",
	"loging2.0_108":"My contract",
	"loging2.0_109":"Order history",
	"loging2.0_110":"Deposit address",
	"loging2.0_111":"Copy address",
	"loging2.0_112":"Precautions：",
	"loging2.0_113":"1. Require 12 blocks to confirm the account, any non-ANT assets can not be retrieved after recharging to ANT address!",
	"loging2.0_114":"2. Your Deposit address is equivalent to your bank account. If you want to transfer digital assets, you only need to provide the address to the other party.",
	"loging2.0_115":"Signing",
	"loging2.0_116":"Withdrawal address",
	"loging2.0_117":"Quantity",
	"loging2.0_118":"Currently available",
	"loging2.0_119":"Support Amount: The minimum Withdrawal amount is 1 ANT.",
	"loging2.0_120":"Withdrawal restrictions: Your 24H Withdrawal quota is 10000 ANT.",
	"loging2.0_121":"Withdrawal miner fee: varies depending on the miner's fee you choose to consume.",
	"loging2.0_122":"Withdrawal address: Your Withdrawal address is the Deposit address of your trading platform account. Each coin type in each trading platform corresponds to an address; to refer your assets from the wallet to the trading platform, you only need to fill in the corresponding trading platform. The corresponding deposit type of the coin type can be.",
	"loging2.0_123":"Confirm",
	"loging2.0_124":"Miner fee",
	"loging2.0_125":"Confirm",
	"loging2.0_126":"Extract all",
	"loging2.0_127":"Miner fee",
	"loging2.0_128":"The transaction is expected to be completed within one hour.",
	"loging2.0_129":"Slow",
	"loging2.0_130":"Natural",
	"loging2.0_131":"Fast",
	"loging2.0_132":"Signing mining",
	"loging2.0_133":"Number of contracts",
	"loging2.0_134":"Contracted object",
	"loging2.0_135":"Sign all",
	"loging2.0_136":"sign contract",
	"loging2.0_137":"Quantity limit: The number of single sign-offs should be greater than or equal to 100 ANT.",
	"loging2.0_138":"About extraction: The principal can be raised at any time.",
	"loging2.0_139":"Miner fee: varies depending on the miner's fee you choose to consume.",
	"loging2.0_140":"Contracted object: refers to the type of mining coin you want to participate in. After selecting the coin type, you can participate in the mining of the corresponding coin type; currently only support ANT mining, and will join the mining activities of various mainstream mining coins.",
	"loging2.0_141":"My contract",
	"loging2.0_142":"Computing contract",
	"loging2.0_143":"ICO contract",
	"loging2.0_144":"ALL",
	"loging2.0_145":"One-click cancellation",
	"loging2.0_146":"One-click collection",
	"loging2.0_147":"ALL",
	"loging2.0_148":"Preheating",
	"loging2.0_149":"Ongoing",
	"loging2.0_150":"Ended",
	"loging2.0_151":"History",
	"loging2.0_152":"Each ID restriction 10000",
	"loging2.0_153":"Confirm",
	"loging2.0_154":"Preheating",
	"loging2.0_155":"Ongoing",
	"loging2.0_156":"Ended",
	"loging2.0_157":"History",
	"loging2.0_158":"Crowdfunding record",
	"loging2.0_159":"type",
	"loging2.0_160":"Crowdfunding",
	"loging2.0_161":"date",
	"loging2.0_162":"Amount",
	"loging2.0_163":"Project details",
	"loging2.0_164":"ANT Token",
	"loging2.0_165":"Total amount (ANT)",
	"loging2.0_166":"Already involved (ANT)",
	"loging2.0_167":"The remaining number of days",
	"loging2.0_168":"Project Introduction",
	"loging2.0_169":"white paper",
	"loging2.0_170":"Please enter the quantity purchased",
	"loging2.0_171":"Pie",
	"loging2.0_172":"Buy now",
	"loging2.0_173":"change the password",
	"loging2.0_174":"Current private key password",
	"loging2.0_175":"new password",
	"loging2.0_176":"Repeat new password",
	"loging2.0_177":"contract",
	"loging2.0_178":"APP Scan Download Our App",
	"loging2.0_179":"Together to Build a Global Business Alliance",
	"loging2.0_180":"My invitation code",
	"loging2.0_181":"&nbsp;&nbsp;&nbsp;&nbsp;ANT Token, based on serving the real economy, empowering traditional industries, and using Token to connect merchants and users to form a major business alliance, bid farewell to the era of fighting alone and fighting alone. <br />&nbsp;&nbsp;&nbsp;&nbsp;ANT is committed to creating a safe, efficient and transparent Token economic application system, which allows merchants and users to form a community of interests, and ultimately realizes that merchant products are not for sale. Users can purchase products with discounts and enjoy the mutual benefit of merchants' dividends. Win mode. ANT is a community-based organization that is shared, shared, and shared by all ANT Token holders and affiliates.<br />&nbsp;&nbsp;&nbsp;&nbsp;The ANT Foundation was launched on September 1, 2018. On September 5, it submitted project white papers, certificates of non-securitization and relevant information on the terms of private placement to the relevant departments in Singapore. It was formally approved on December 3, 2008, thus declaring the establishment of a non-profit organization.<br />&nbsp;&nbsp;&nbsp;&nbsp;The ANT Foundation is committed to building a global business alliance, opening up the dual Toekn economy and empowering the physical industry.<br />&nbsp;&nbsp;&nbsp;&nbsp;ANT Token: Serving the real economy, it is a proof of the rights of blockchain technology. It is committed to helping merchants not sell their products, and consumers are not spending money in the new economic system.<br />&nbsp;&nbsp;&nbsp;&nbsp;ANT Coin: Focusing on the research and development of blockchain technology, it is committed to solving the problems of slow transfer of blockchain chain, monopoly of computing power, inconvenient storage, cumbersome transactions, and difficult landing. The ANT Coin main chain is issued with 5 billion pieces of equity mining and main node distribution, of which 39% (1.95 billion pieces) of Chuangshi block pre-digging are issued in three phases through the recruitment of co-founders. The remainder is mined by pos mining and main node mining.",
	"loging2.0_182":"AboutUs",
	"loging2.0_183":"Set the wallet name",
	"loging2.0_184":"Not less than 8 characters, it is recommended to mix large letters and numbers",
	"loging2.0_185":"Enter your password again",
	"loging2.0_186":"Export mnemonic",
	"loging2.0_187":"Save offline",
	"loging2.0_188":"Please copy and paste the keystore file to a safe, offline place to save. Do not save to email, notepad, web navigation, chat tools, etc., very dangerous.",
	"loging2.0_189":"Do not use network transmission",
	"loging2.0_190":"Do not transfer Keystore files through network tools. Once hacked, it will cause irreparable asset loss.",
	"loging2.0_191":"Password safe save",
	"loging2.0_192":"If you need to save online, it is recommended to save the keystore with a password security software with a higher security level.",
	"loging2.0_193":"copy Keystore",
	"loging2.0_194":"Sent successfully",
	"loging2.0_195":"The amount does not match",
	"loging2.0_196":"Number does not match",
	"loging2.0_197":"Private key password error",
	"loging2.0_198":"The input is free",
	"loging2.0_199":"Mall",
	"loging2.0_200":"combustion",
	"loging2.0_201":"Private key password error",
	"loging2.0_202":"Message",
	"loging2.0_203":"Deposit in",
	"loging2.0_204":"Not yet open",
	"loging2.0_205":"Crowdfunding",
	"loging2.0_206":"Record",
	"loging2.0_207":"My lock",
	"loging2.0_208":"Official website",
	"loging2.0_209":"white paper",
	"loging2.0_210":"Browser",
	"loging2.0_211":"RUB Service",
	"loging2.0_212":"Current exchange rate≈",
	"loging2.0_213":"Participate in crowdfunding",
	"loging2.0_214":"Crowdfunding rules",
	"loging2.0_215":"Recent crowdfunding",
	"loging2.0_216":"Waiting",
	"loging2.0_217":"completed",
	"loging2.0_218":"Pull up to show more",
	"loging2.0_219":"loading",
	"loging2.0_220":"Already loaded all",
	"loging2.0_221":"Pull down can refresh",
	"loging2.0_222":"Release immediate refresh",
	"loging2.0_223":"Refreshing",
	"loging2.0_224":"Crowdfunding rules:",
	"loging2.0_225":"Crowdfunding is the use of cross-chain trading technology to achieve free and fast exchange between different digital assets. Crowdfunding will complete the exchange on the smart contract of the blockchain without trusting third parties.",
	"loging2.0_226":"Crowdfunding ratio:",
	"loging2.0_227":"The proportion of crowdfunding is obtained in real time by the backend server from the blockchain smart contract.",
	"loging2.0_228":"Deal rule:",
	"loging2.0_229":"After submitting the crowdfunding order, it will be broadcast to the blockchain network of Ethereum and redemption objects waiting for the miners to pack. After the crowdfunding success, you will see the record of this order in the crowdfunding record.",
	"loging2.0_231":"Details(RUB)",
	"loging2.0_232":"Payment amount:",
	"loging2.0_233":"Exchange amount:",
	"loging2.0_234":"Payment address:",
	"loging2.0_235":"Exchange address:",
	"loging2.0_236":"Transaction number:",
	"loging2.0_237":"confirmed",
	"loging2.0_238":"My lock(RUB)",
	"loging2.0_239":"Release time:",
	"loging2.0_240":"Number of locks:",
	"loging2.0_241":"Total released:",
	"loging2.0_242":"Transaction number:",
	"loging2.0_243":"Extractable RUB",
	"loging2.0_244":"Receiving income",
	"loging2.0_245":"Recommendation code",
	"loging2.0_246":"language settings",
	"loging2.0_247":"exchange",
	"loging2.0_248":"IEX",
	"loging2.0_249":"Participate in IEX",
	"loging2.0_250":"IEX rules",
	"loging2.0_251":"Recently IEX",
	"loging2.0_252":"IEX confirmation",
	"loging2.0_253":"Redeem RUB rules:",
	"loging2.0_254":"Each ANT account is proportional to the amount of assets to obtain the corresponding redemption limit; <br /> every 10 assets are exchanged for a RUB quota.",
	"loging2.0_255":"Exchange ratio:",
	"loging2.0_256":"1 A pass = 1 CNY<br /> Converted according to the price of real-time RUB",
	"loging2.0_257":"Exchange lock:",
	"loging2.0_258":"The lock time is calculated from the RUB online trading platform; <br /> locks the warehouse for 10 months, releasing 10% per month. <br /> Note: Each account requires the 0.1ETH activation redemption function.",
	"loging2.0_259":"Exchange limit:",
	"loging2.0_260":"Each account redemption limit: no more than 500,000 pieces; <br /> platform total exchange limit: no more than 500 million pieces.",
	"loging2.0_261":"Sorry, ANT is working hard to build. Please wait patiently~",
	"loging2.0_262":"IEX to WBC rules:",
	"loging2.0_263":"Subscription time September 30th 10:00-October 6th 23:59<br/>The total subscription amount is 5 billion WBC<br/>Each ANT account can be subscribed to WBC by ANT certificate or assets",
	"loging2.0_264":"IEX ratio:",
	"loging2.0_265":"1 Token = 1 WBC<6/>6 assets = 1 WBC",
	"loging2.0_266":"The subscription has ended",
	"loging2.0_267":"Subscription quantity:",
	"loging2.0_268":"Subscription limit per account: no more than 50,000 pieces. The total subscription limit for the first period: no more than 500 million pieces.",
	"loging2.0_269":"Current round of exchanges:",
	"loging2.0_270":"Binding address",
	"loging2.0_271":"Local Ruby wallet",
	"loging2.0_272":"Installing, please return to the desktop to view the installation status",
	"loging2.0_273":"Immediate trust",
	"loging2.0_274":"Please wait for the download to end, wallet binding",
	"loging2.0_275":"Wallet address cannot be empty",
	"loging2.0_276":"Bind immediately",
	"loging2.0_277":"Please enter the wallet address",
	"loging2.0_278":"Rub wallet address",
	"loging2.0_279":"Current function needs to jump to Ruby App",
	"loging2.0_280":"If not downloaded, please download and install first.",
	"loging2.0_281":"download immediately",
}